### ISSUE TITLE
Invalid timeout (0.0, 0.0). Pass a (connect, read) timeout tuple, or a single float to set both timeouts to the same value

### ISSUE THREAD

**Issue by NGorsel** [yzwetsloot/BolBot#9]
Somehow I receive an error around the two functions : ThreadPoolExecutor and ProcessPoolExecutor. I did some reading on them and I do understand what their function is. However, somehow the middle line in in the following part of code causing an invalid timeout (0.0, 0.0) error. Some

```
                with ThreadPoolExecutor(max_workers=THREAD_COUNT) as executor:
                    downloads = executor.map(produce, batch)

                downloads = chunks(list(downloads), int(BATCH_SIZE / cpu_count()))

                with ProcessPoolExecutor(max_workers=PROCESS_COUNT) as executor:
                    result = executor.map(process, downloads)
```

I have no idea why this error is caused. In the config.json I gave the following attributes the following values: batch_size = 10, thread_count = 50, process_count = 3, timeout =1. 

If I print the batch just before the line that causes the errror I see that the batch consists of a list containing 10 links, as shown below. The cpu_count is also equal to 3, as expected.

`['https://www.bol.com/nl/l/beddengoed/N/14193/?page=1', 'https://www.bol.com/nl/l/beddengoed/N/14193/?page=2', 'https://www.bol.com/nl/l/beddengoed/N/14193/?page=3', 'https://www.bol.com/nl/l/beddengoed/N/14193/?page=4', 'https://www.bol.com/nl/l/beddengoed/N/14193/?page=5', 'https://www.bol.com/nl/l/beddengoed/N/14193/?page=6', 'https://www.bol.com/nl/l/beddengoed/N/14193/?page=7', 'https://www.bol.com/nl/l/beddengoed/N/14193/?page=8', 'https://www.bol.com/nl/l/beddengoed/N/14193/?page=9', 'https://www.bol.com/nl/l/beddengoed/N/14193/?page=10']`

Here is the whole output of my terminal
```
(venv) MacBook-Pro-3:src USER$ python main.py 
2019-12-03 10:43:22,692 - chardet.charsetprober - DEBUG - EUC-JP Japanese prober hit error at byte 30542
2019-12-03 10:43:22,748 - chardet.charsetprober - DEBUG - GB2312 Chinese prober hit error at byte 30544
2019-12-03 10:43:22,802 - chardet.charsetprober - DEBUG - EUC-KR Korean prober hit error at byte 30542
2019-12-03 10:43:22,855 - chardet.charsetprober - DEBUG - CP949 Korean prober hit error at byte 30542
2019-12-03 10:43:22,908 - chardet.charsetprober - DEBUG - Big5 Chinese prober hit error at byte 30544
2019-12-03 10:43:22,962 - chardet.charsetprober - DEBUG - EUC-TW Taiwan prober hit error at byte 30542
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - utf-8  confidence = 0.7525
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - SHIFT_JIS Japanese confidence = 0.01
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - EUC-JP not active
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - GB2312 not active
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - EUC-KR not active
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - CP949 not active
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - Big5 not active
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - EUC-TW not active
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - windows-1251 Russian confidence = 0.01
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - KOI8-R Russian confidence = 0.01
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - ISO-8859-5 Russian confidence = 0.01
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - MacCyrillic Russian confidence = 0.0
2019-12-03 10:43:23,035 - chardet.charsetprober - DEBUG - IBM866 Russian confidence = 0.0
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - IBM855 Russian confidence = 0.01
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - ISO-8859-7 Greek confidence = 0.01
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - windows-1253 Greek confidence = 0.01
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - ISO-8859-5 Bulgairan confidence = 0.01
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - windows-1251 Bulgarian confidence = 0.01
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - TIS-620 Thai confidence = 0.01
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - ISO-8859-9 Turkish confidence = 0.5298867160717968
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - windows-1255 Hebrew confidence = 0.0
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - windows-1255 Hebrew confidence = 0.01
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - windows-1255 Hebrew confidence = 0.01
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - utf-8  confidence = 0.7525
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - SHIFT_JIS Japanese confidence = 0.01
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - EUC-JP not active
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - GB2312 not active
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - EUC-KR not active
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - CP949 not active
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - Big5 not active
2019-12-03 10:43:23,036 - chardet.charsetprober - DEBUG - EUC-TW not active
['138.68.41.90']
2019-12-03 10:43:23,959 - __main__ - INFO - 1 retrieved; start cycle
Traceback (most recent call last):
  File "/Users/USER/Projects/venv/lib/python3.8/site-packages/requests/adapters.py", line 425, in send
    timeout = TimeoutSauce(connect=connect, read=read)
  File "/Users/USER/Projects/venv/lib/python3.8/site-packages/urllib3/util/timeout.py", line 96, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/Users/USER/Projects/venv/lib/python3.8/site-packages/urllib3/util/timeout.py", line 141, in _validate_timeout
    raise ValueError(
ValueError: Attempted to set connect timeout to 0.0, but the timeout cannot be set to a value less than or equal to 0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 153, in <module>
    main()
  File "main.py", line 127, in main
    downloads = chunks(list(downloads), int(BATCH_SIZE / cpu_count()))
  File "/Users/USER/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/Users/USER/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/USER/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/USER/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "main.py", line 68, in produce
    response = requests.get(url, timeout=(CONNECT_TIMEOUT, READ_TIMEOUT), proxies={"https": proxy})
  File "/Users/USER/Projects/venv/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/USER/Projects/venv/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/USER/Projects/venv/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/USER/Projects/venv/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/USER/Projects/venv/lib/python3.8/site-packages/requests/adapters.py", line 431, in send
    raise ValueError(err)
ValueError: Invalid timeout (0.0, 0.0). Pass a (connect, read) timeout tuple, or a single float to set both timeouts to the same value
(venv) MacBook-Pro-3:src USER$ 
```

Any help is highly appreciated! Thanks in advance :-)

**Comment by yzwetsloot** [comment]
Guessing from the trace I assume you might have left the `connect_timeout` and `read_timeout` config parameters at 0.0. These should be something different, otherwise `requests` will not be able to make the request. I suggest for the first time, you set both of these to 1.5. You can later try to figure out what values result in the best performance using empirical analysis.
